### PR TITLE
fix(Accordion): not expanding

### LINKED ISSUE #3561: Accordion Component Broken in Latest Version
## Expected Behavior

The accordion component should open on click when set up correctly (e.g. as outlined in [this post](https://github.com/kiwicom/orbit/issues/2691)). This was working correctly for us previously but has become broken in one of the recent versions (over past couple of months).

I have tried implementing the simple example from that old issue to confirm it's not something specific to how we are using the component (despite our implementation having worked correctly previously).

## Current Behavior

The accordion section does not open on click.

## Steps to Reproduce

Try implementing accordion as outlined in this [old issue](https://github.com/kiwicom/orbit/issues/2691). The accordion will not open.

### PR DESCRIPTION
**Pull request by Nadhum**
# This Pull Request meets the following criteria:

- [x] Tests have been added/adjusted for my new feature
- [x] New Components are registered in index.js of my project
- [x] New Components has both `.flow` and `d.ts` files and are exported in `index.js.flow` and `index.d.ts`

Fixes #3561 

### Description
An id update was missed during some id work, which resulted in the accordion checking against the wrong id to determine whether it should be expanded or not.

Tested in storybook

### CODE REVIEW

File: packages/orbit-components/src/Accordion/index.jsx [hunk 1]
```diff
@@ -37,7 +37,7 @@ const Accordion = ({
 
           const { id: innerId } = item.props;
           // Determine if section is expanded
-          const isExpanded = expandedSection === id;
+          const isExpanded = expandedSection === innerId;
```
Comment (Nadhum) [inline packages/orbit-components/src/Accordion/index.jsx:40]: This is the actual fix.

File: .github/contribution/README.md [hunk 2]
```diff
@@ -40,7 +40,7 @@
 First, you need to build the project:
 
 ```
-yarn build
+yarn build-ci
```
Comment (mainframev) [inline .github/contribution/README.md:43]: could you remove that? we already building the tokens during the build, so no need in that ;)

Comment (Nadhum) [reply .github/contribution/README.md:43]: This is the README in the contribution guide, there is no step yarn build, I thought it's out of date? Am I missing something here?

Comment (Nadhum) [reply .github/contribution/README.md:43]: The steps to start with development here https://github.com/kiwicom/orbit/blob/master/.github/contribution/README.md#starting-with-development
should be 
```
yarn build-ci
yarn dev
```
right? or at least that's what I had to do, as there was no target for yarn build
